### ISSUE TITLE
ObjectVM in Objective C

### ISSUE THREAD

**Issue by SafelySwift** [JLWalsh/ObjectVM#1]
This looks really cool! However since it is C it might be a hard for new programmers to understand and -in my case- impossible to use. This is not so much an Issue request as it is a Feature request.

**Comment by JLWalsh** [comment]
I understand your concern, however I am as unfamiliar to Objective C as you are unfamiliar to C! I have chosen C not because I prefer this language over another, but because it is extremely portable when used correctly. There's a good learning curve to it, but it is well worth learning!

**Comment by SafelySwift** [comment]
I think C should be very similar enough that you can copy and paste (however you will get warning on all calls to free memory so you will have to turn off ARC). However I am considering starting to learn C++ so that I can run Swizzle ultra fast. Also C++ is just a good language all around. 

Best,
Ethan

From, Ethan Uppal
Sent from my iPhone
Please excuse typos

**Comment by JLWalsh** [comment]
> I think C should be very similar enough that you can copy and paste (however you will get warning on all calls to free memory so you will have to turn off ARC). However I am considering starting to learn C++ so that I can run Swizzle ultra fast. Also C++ is just a good language all around.

Yep, learning C++ would be well worth it, especially since developing languages tends to require more low-level control for things like memory management. I have to say that I am prejudiced against Objective C though, because I really, really dislike the syntax!
